package A2;

import java.util.ArrayList;
import java.util.List;

public class Driver {
    public static void main(String[] args) {

        /*
        Create a library;
         */
        Library lib = new Library();


        /*
        f1 finds out all the English movies from Library lib.
        The WatchList all_English contains all the English movies generated by f1.
         */

        Feature<Movie> f1 = new Feature<Movie>() {
            @Override
            public List<Movie> toAdd(Library lib) {
                ArrayList<Movie> list = new ArrayList<>();
                for (Movie m : lib.getMovies()) {
                    if (m.getLanguage().compareTo("English") == 0) {
                        list.add(m);
                    }
                }
                return list;
            }
        };

        WatchList<Movie> all_English = lib.mvList_generation("English movies", f1);


        /*
        Use the Feature f2 to get 10 episodes from the first TVShow in the library, and generate a watchlist with it.
         */

        Feature<Episode> f2 = new Feature<Episode>() {
            @Override
            public List<Episode> toAdd(Library lib) {
                ArrayList<Episode> list = new ArrayList<>();
                TVShow tvs = lib.getTVSs().get(0);
                for (int i = 0; i < 10; i++) {
                    list.add(tvs.get_Episode(i));
                }
                return list;
            }
        };

        WatchList<Episode> first_10  = lib.epiList_generation("first_10_episodes", f2);

    }
}
